### ISSUE TITLE
New Install - python migrate.py syncbd Throws Exception

### ISSUE THREAD

**Issue by mguidone** [stormpath/stormpath-django#37] opened 2015-05-06 18:42 UTC
Tried installing and using for the first time. Followed instructions and got up to the syncdb step and got the following...

Operations to perform:
  Synchronize unmigrated apps: messages, django_extensions, staticfiles
  Apply all migrations: sessions, tastypie, contenttypes, admin, django_stormpath, coreAPI, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying django_stormpath.0001_initial... OK
The following content types are stale and need to be deleted:

    auth | user

Any objects related to these content types by a foreign key will also be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes

If I answer no.. All usage of the User fails.
If I answer yes I get:

  File "/.../virtual_environment/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/.../virtual_environment/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_stormpath_stormpathuser_user_permissions
django.db.utils.OperationalError: no such table: django_stormpath_stormpathuser_user_permissions

**Comment by mguidone** [comment] 2015-05-06 22:08
What I have installed...
behave (1.2.5)
Django (1.8.1)
django-extensions (1.5.2)
django-sslify (0.2.7)
django-stormpath (1.0.1)
django-tastypie (0.12.1)
oauthlib (0.7.2)
parse (1.6.6)
parse-type (0.3.4)
pip (6.1.1)
PyJWT (1.1.0)
pyslack (0.1.3)
python-dateutil (2.4.2)
python-mimeparse (0.1.4)
redis (2.10.3)
requests (2.7.0)
requests-oauthlib (0.5.0)
setuptools (15.0)
six (1.9.0)
stormpath (2.0.5)
suds-jurko (0.6)

**Comment by omgitstom** [comment] 2015-05-06 22:26
Hi @mguidone, thanks for the report! I manage product @ Stormpath. I was just getting ready to ask you what version of django and what dependencies you have installed, so great timing! I haven't seen this exception before, or I could help you understand what the issue is, so we need to wait for my python gurus. 

@avojnovicDk @rdegges any suggestions?

Just to give you some visibility into timing,@rdegges is out of the office until next week and @avojnovicDk is on the other side of the world, so I don't think we can get you a response by today before COB in the US.

**Comment by mguidone** [comment] 2015-05-06 22:37
I was using the stormpath module and was just about to do this kind of integration myself and found this module. First Thought: "That'll save me some time!" I would dig deeper into the migration if I didnt have  other things I needed to get done. Thanks for checking in and keeping me informed its appreciated!

**Comment by DanielStevenLewis** [comment] 2015-05-07 22:26
Just encountered a very similar issue. Sent a message to support and then found this ticket.

I'm getting:

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

Operations to perform:
  Synchronize unmigrated apps: LogIt, messages, pygments, staticfiles, rest_framework
  Apply all migrations: snippets, django_stormpath, dynamic_forms, auth, admin, sessions, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying django_stormpath.0001_initial... OK
The following content types are stale and need to be deleted:

    auth | user

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_stormpath_stormpathuser_user_permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/garylewis/Documents/Work/RightBlue/LogIt-Django/LogIt/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 225, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/contrib/contenttypes/management.py", line 81, in update_contenttypes
    ct.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/base.py", line 872, in delete
    collector.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/deletion.py", line 292, in delete
    qs._raw_delete(using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 549, in _raw_delete
    sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/subqueries.py", line 78, in delete_qs
    self.get_compiler(using).execute_sql(NO_RESULTS)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 837, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_stormpath_stormpathuser_user_permissions
Finished "[path to my project was here]/manage.py syncdb" execution.

______

pip list
Django (1.8.1)
django-filter (0.9.2)
django-stormpath (1.0.1)
djangorestframework (3.1.1)
Markdown (2.6.2)
oauthlib (0.7.2)
pip (6.1.1)
PyJWT (1.1.0)
python-dateutil (2.4.2)
requests (2.7.0)
requests-oauthlib (0.5.0)
setuptools (12.0.5)
six (1.9.0)
stormpath (2.0.5)
virtualenv (12.1.1)

**Comment by omgitstom** [comment] 2015-05-08 21:44
@mguidone we reproduced the issue and the fix for the migration script is in https://github.com/stormpath/stormpath-django/pull/38  This will be merged sometime early next week.  If you are comfortable pulling in the changes to see if it resolves it, feel free to.

@DanielStevenLewis We didn't see that exact error, but that doesn't mean that we may have resolved it. If you are comfortable pulling in the changes in https://github.com/stormpath/stormpath-django/pull/38 to see it is resolves it, feel free to.  Otherwise, Stormpath may have to dig in a little deeper.

Thanks!

**Comment by mguidone** [comment] 2015-05-09 14:04
Thank You. I'll give it a shot tomorrow afternoon

**Comment by DanielStevenLewis** [comment] 2015-05-11 14:08
Thanks guys. I copied the contents of https://raw.githubusercontent.com/avojnovicDk/stormpath-django/stale-migrations-fix/django_stormpath/migrations/0001_initial.py into the corresponding file in my project but I'm still getting the following error upon running syncdb.

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

Operations to perform:
  Synchronize unmigrated apps: staticfiles, rest_framework, messages, pygments, LogIt
  Apply all migrations: sessions, django_stormpath, contenttypes, admin, dynamic_forms, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
The following content types are stale and need to be deleted:

    auth | user

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_stormpath_stormpathuser_user_permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/garylewis/Documents/Work/RightBlue/LogIt-Django/LogIt/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 225, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/contrib/contenttypes/management.py", line 81, in update_contenttypes
    ct.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/base.py", line 872, in delete
    collector.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/deletion.py", line 292, in delete
    qs._raw_delete(using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 549, in _raw_delete
    sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/subqueries.py", line 78, in delete_qs
    self.get_compiler(using).execute_sql(NO_RESULTS)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 837, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_stormpath_stormpathuser_user_permissions
Finished "/Users/garylewis/Documents/Work/RightBlue/LogIt-Django/LogIt/manage.py syncdb" execution.

**Comment by avojnovicDk** [comment] 2015-05-11 15:51
Hi, @DanielStevenLewis ! Thank you for the traceback. Can you please paste content from the django_migrations table? It would help me reproduce that.

**Comment by DanielStevenLewis** [comment] 2015-05-11 15:57
Sorry I'm very new to Django. How do I get that content?

**Comment by avojnovicDk** [comment] 2015-05-11 16:10
It's just a table in your sqlite database called "django_migrations". Django uses it to track applied migrations. So, it's just `SELECT * FROM django_migrations;` on your DB. Thanks!

**Comment by avojnovicDk** [comment] 2015-05-12 10:11
I think I know what happened, or at least this is how I managed to reproduce
> django.db.utils.OperationalError: no such table: django_stormpath_stormpathuser_user_permissions

error.
First, you ran `syncdb` without django_stormpath app. That created Django user tables in the DB. Then, you added django_stormpath app and got error. Tried with new https://raw.githubusercontent.com/avojnovicDk/stormpath-django/stale-migrations-fix/django_stormpath/migrations/0001_initial.py and got error again. Am I right? That is because you first have to revert the old 0001_initial migration before applying the new one.
So, this is how I made this to work:
1. I reverted 0001_initial.py code to the one from 1.0.1 version, so Django knows what migration to revert.
2. I reverted that migration with `python manage.py migrate django_stormpath zero`. It produced
> django.db.utils.OperationalError: no such table: django_admin_log

error because it unapplied admin.0001_initial as well.
3. I copied new https://raw.githubusercontent.com/avojnovicDk/stormpath-django/stale-migrations-fix/django_stormpath/migrations/0001_initial.py , so the new migration will be applied.
4. I applied both django_stormpath.0001_initial and admin.0001_initial with `python manage.py migrate`.

Also, if you are doing this in your development environment, it is probably easier to just start with fresh DB, use https://raw.githubusercontent.com/avojnovicDk/stormpath-django/stale-migrations-fix/django_stormpath/migrations/0001_initial.py and let Django apply all the migrations from there.

I hope this helps.

**Comment by rdegges** [comment] 2015-05-12 23:42
Closing this as I just released the fix for this into 1.0.2. Should be good for upgrade =)

**Closed by rdegges** 2015-05-12 23:42 UTC

**Comment by DanielStevenLewis** [comment] 2015-05-13 17:46
Thanks for looking into it. We fixed the problem when we installed a different database.

**Comment by mguidone** [comment] 2015-05-13 21:51
All is well, thanks
